<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>fo</description>
   <name>Footer</name>
   <tag></tag>
   <elementGuidId>a161bd02-7dc2-40a4-a020-1287b2b50b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
